# Generated by Django 5.0.14 on 2025-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0007_postcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cached_author_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='cached_author_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
