# Generated by Django 5.0.14 on 2025-12-01 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0008_post_cached_author_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='cached_author_name',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='cached_author_name',
        ),
    ]
